name: decoo-beta-ci

on:
  push:
    branches:
    - 'beta'

jobs:
  docker:
    if: github.repository == 'decooio/ipfs-w3auth'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DECOO_PAT }}

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build bundle
      run: yarn build

    - name: Dockerize and push
      run: |
        ./dockerize.sh
        docker push ghcr.io/decooio/ipfs-w3auth-gateway-beta:latest
